#!/usr/bin/env bash
# Displays information about the file /etc/passwd

if [ -e "/etc/passwd" ]

then

  echo "/etc/passwd file exists"

  if [ -s "/etc/passwd" ]

  then

    echo "/etc/passwd file is not empty"

  else

    echo "/etc/passwd file is empty"

  fi



  if [ -f "/etc/passwd" ]

  then

    echo "/etc/passwd is a regular file"

  fi

else

  echo "/etc/passwd file does not exist"

fi
