#!/usr/bin/env bash
# Displays information about the file /etc/school

if [ -e "/etc/school" ]

then

  echo "/etc/school file exists"

  if [ -s "/etc/school" ]

  then

    echo "/etc/school file is not empty"

  else

    echo "/etc/school file is empty"

  fi



  if [ -f "/etc/school" ]

  then

    echo "/etc/school is a regular file"

  fi

else

  echo "/etc/school file does not exist"

fi
